In [2]:
import numpy as np
import pandas as pd
from scipy.stats import ttest_ind_from_stats
#from statsmodels.stats.weightstats import ttest_ind_from_stats
import urllib.request

In [3]:
## saving the appropriate NYC Open Data URLs to variables
URL16 = 'https://data.cityofnewyork.us/api/views/8u86-bviy/rows.csv?accessType=DOWNLOAD'
URL15 = 'https://data.cityofnewyork.us/api/views/hypw-js3b/rows.csv?accessType=DOWNLOAD'
URL14 = 'https://data.cityofnewyork.us/api/views/jzst-u7j8/rows.csv?accessType=DOWNLOAD'
URL13 = 'https://data.cityofnewyork.us/api/views/rgfe-8y2z/rows.csv?accessType=DOWNLOAD'
URL12 = 'https://data.cityofnewyork.us/api/views/5gde-fmj3/rows.csv?accessType=DOWNLOAD'

## saving the appropriate label for BBL to variables for each year
BBL16 = 'BBL - 10 digits'
BBL15 = 'NYC Borough, Block and Lot (BBL)'
BBL14 = 'BBL'
BBL13 = 'BBL'
BBL12 = 'BBL'

## saving the appropriate label for Site EUI to variables for each year
EUI16 = 'Site EUI (kBtu/ft²)'
EUI15 = 'Site EUI (kBtu/ft²)'
EUI14 = 'Site EUI(kBtu/ft2)'
EUI13 = 'Site EUI(kBtu/ft2)'
EUI12 = 'Site EUI(kBtu/ft2)'

In [24]:
# merges two year's worth of LL84 data on BBL and returns a data frame listing 
# the Site EUI difference value for each BBL that contains data for both years  
def difference(URL1, URL2, BBL_name1, BBL_name2, EUI_name1, EUI_name2):
    # loading building energy benchmarking data into dataframes
    year1 = pd.read_csv(URL1)
    year2 = pd.read_csv(URL2)
    
    # replacing the 'Not Available' values with NaN
    year1.replace('Not Available', np.nan, inplace=True)
    year1.replace('See Primary BBL', np.nan, inplace=True)
    year1.replace('NA', np.nan, inplace=True)
    year2.replace('NA', np.nan, inplace=True)
    year2.replace('Not Available', np.nan, inplace=True)
    year2.replace('See Primary BBL', np.nan, inplace=True)
    
    # making sure Site EUI is a float
    year1[EUI_name1] = year1[EUI_name1].astype(float)
    year2[EUI_name2] = year2[EUI_name2].astype(float)    
    
    # removing records with unrealistic Site EUI values
    year1.drop(year1[year1[EUI_name1] > 300].index, inplace=True)
    year2.drop(year2[year2[EUI_name2] > 300].index, inplace=True)
    year1.drop(year1[year1[EUI_name1] < 0].index, inplace=True)
    year2.drop(year2[year2[EUI_name2] < 0].index, inplace=True)
            
    # dropping every column but BBL and Site Energy Use Intensity
    year1 = year1.filter(items=[BBL_name1, EUI_name1])
    year2 = year2.filter(items=[BBL_name2, EUI_name2])
    
    # forcing BBLs out of scientific notation and then saving as string
    # then storing length of BBL string in new column
    year1['length'] = year1[BBL_name1].astype(str).str.len()
    year2['length'] = year2[BBL_name2].astype(str).str.len()
    
    year1.dropna(inplace=True)
    year2.dropna(inplace=True)
    
    # Any record with more than 12 digits includes more than one tax lot in a report
    # This is a difficult set-up to work with, so I am deleting those rows outright
    year1.drop(year1[year1['length'] >12].index, inplace=True)
    year2.drop(year2[year2['length'] >12].index, inplace=True)
    
    year1[BBL_name1] = pd.to_numeric(year1[BBL_name1], errors='coerce')#.astype(int)
    year2[BBL_name2] = pd.to_numeric(year2[BBL_name2], errors='coerce')
    
    year1 = year1.rename(columns={BBL_name1: 'BBL1', EUI_name1: 'SiteEUI1'})
    year2 = year2.rename(columns={BBL_name2: 'BBL2', EUI_name2: 'SiteEUI2'})
        
    ##year1 = year1.rename(columns={[0]: 'BBL1'})#,[1]: 'SiteEUI1', [2]: 'length1'})
    ##year2 = year2.rename(columns={[0]: 'BBL2'})#, [1]: 'SiteEUI2', [2]: 'length2'})    
    
    # merging on BBL to create dataset with Site EUI values for preRCx and postRCx years
    ##pop = year1.merge(year2, left_on=BBL_name1, right_on=BBL_name2, how='outer')
    
    
    
    pop = year1.merge(year2, left_on='BBL1', right_on='BBL2', how='inner')
    ##pop = pd.merge(year1, year2, how='inner', on=['BBL1', 'BBL2'], )

    ##pop = pop.rename(columns={BBL_name1: 'BBL1', EUI_name1: 'SiteEUI1', BBL_name2: 'BBL2', EUI_name2: 'SiteEUI2'})
    
    #dropping length column
    #pop.drop(['length1', 'length2'], axis=1, inplace=True)
    
    # dropping all rows with NaN
    ##pop.dropna(inplace=True)
    
    # creating a "difference" column which shows the change in Site EUI from year 1 to year 2
    pop['difference'] = pop['SiteEUI2'] - pop['SiteEUI1']
    return pop

In [27]:
pop12_14 = difference(URL12, URL14, BBL12, BBL14, EUI12, EUI14)
#pop13_15 = difference(URL13, URL15, BBL13, BBL15, EUI13, EUI15)
#pop14_16 = difference(URL14, URL16, BBL14, BBL16, EUI14, EUI16)

pop12_14

,BBL1,SiteEUI1,length_x,BBL2,SiteEUI2,length_y,difference
0,1000047501,102.0,10,1000047501,149.0,10,47.0
1,1000057501,119.6,10,1000057501,113.8,10,-5.8
2,1000090001,99.5,10,1000090001,81.3,10,-18.2
3,1000090014,79.7,10,1000090014,80.8,10,1.1
4,1000090029,139.4,10,1000090029,136.2,10,-3.2
5,1000100014,134.5,10,1000100014,113.0,10,-21.5
6,1000100023,102.8,10,1000100023,106.8,10,4.0
7,1012900021,71.8,10,1012900021,83.0,10,11.2
8,1000130001,65.7,10,1000130001,65.4,10,-0.3
9,1000130005,80.1,10,1000130005,99.8,10,19.7
10,1011200022,62.4,10,1011200022,65.4,10,3.0
11,1000157501,28.7,10,1000157501,66.6,10,37.9
12,1000157501,50.0,10,1000157501,66.6,10,16.6
13,1000157502,50.1,10,1000157502,78.0,10,27.9
14,3068180025,49.7,10,3068180025,66.9,10,17.2
15,1011860091,60.9,10,1011860091,68.6,10,7.7
16,1000160100,67.5,10,1000160100,0.3,10,-67.2
17,1000160120,111.2,10,1000160120,113.6,10,2.4
18,1000160150,31.4,10,1000160150,10.4,10,-21.0
19,1000160180,112.4,10,1000160180,108.7,10,-3.7
20,1000160185,96.3,10,1000160185,89.9,10,-6.4
21,1000160190,70.3,10,1000160190,50.0,10,-20.3
22,1000160195,100.5,10,1000160195,105.9,10,5.4
23,1000160200,80.9,10,1000160200,96.6,10,15.7
24,1000160210,72.2,10,1000160210,77.5,10,5.3
25,1000160225,148.3,10,1000160225,113.8,10,-34.5
26,1000160260,111.5,10,1000160260,109.7,10,-1.8
27,1000167501,64.9,10,1000167501,77.0,10,12.1
28,1000167502,71.5,10,1000167502,41.1,10,-30.4
29,1009087501,68.4,10,1009087501,88.7,10,20.3
...,...,...,...,...,...,...,...
9284,5028930001,93.3,10,5028930001,62.0,10,-31.3
9285,5028940001,84.3,10,5028940001,68.8,10,-15.5
9286,5029220020,105.8,10,5029220020,91.7,10,-14.1
9287,5030950021,49.5,10,5030950021,51.4,10,1.9
9288,5030950021,63.9,10,5030950021,51.4,10,-12.5
9289,5031570001,54.3,10,5031570001,49.8,10,-4.5
9290,5033070025,82.6,10,5033070025,85.7,10,3.1
9291,4051810036,11.1,10,4051810036,12.9,10,1.8
9292,5035437501,83.5,10,5035437501,24.5,10,-59.0
9293,5039690001,49.0,10,5039690001,57.3,10,8.3
9294,5039830001,86.1,10,5039830001,81.1,10,-5.0
9295,5039830001,93.8,10,5039830001,81.1,10,-12.7
9296,5039830001,51.1,10,5039830001,81.1,10,30.0
9297,5039830045,57.7,10,5039830045,61.0,10,3.3
9298,5039830045,56.1,10,5039830045,61.0,10,4.9
9299,5039830045,57.6,10,5039830045,61.0,10,3.4
9300,5039830065,68.1,10,5039830065,68.8,10,0.7
9301,5039830065,72.3,10,5039830065,68.8,10,-3.5
9302,5013800001,94.0,10,5013800001,105.5,10,11.5
9303,5040010001,164.6,10,5040010001,93.8,10,-70.8
9304,5052360031,72.9,10,5052360031,169.5,10,96.6
9305,5054970007,196.5,10,5054970007,266.6,10,70.1
9306,5054970007,237.3,10,5054970007,266.6,10,29.3
9307,5059650084,9.4,10,5059650084,15.5,10,6.1
9308,5063320006,58.7,10,5063320006,53.3,10,-5.4
9309,5070670117,13.3,10,5070670117,16.2,10,2.9
9310,5071000028,264.8,10,5071000028,229.1,10,-35.7
9311,5074810001,80.8,10,5074810001,84.9,10,4.1
9312,5075110001,113.9,10,5075110001,164.5,10,50.6
9313,5079910100,135.9,10,5079910100,161.6,10,25.7

In [67]:
# renaming SiteEUI columns to be more descriptive
pop12_14.rename(index=str, columns={"SiteEUI1": "SiteEUI2012", "SiteEUI2": "SiteEUI2014"},  inplace = True)
pop13_15.rename(index=str, columns={"SiteEUI1": "SiteEUI2013", "SiteEUI2": "SiteEUI2015"},  inplace = True)
pop14_16.rename(index=str, columns={"SiteEUI1": "SiteEUI2014", "SiteEUI2": "SiteEUI2016"},  inplace = True)

# dropping length columns
'''pop12_14.drop(['length1'], axis=1, inplace=True)
pop13_15.drop(['length1', 'length2'], axis=1, inplace=True)
pop14_16.drop(['length1', 'length2'], axis=1, inplace=True)'''
pop12_14.head()

           BBL1 SiteEUI2012 length1          BBL2 SiteEUI2014 length2
0  1.000010e+09       False    True  1.000010e+09       False    True
1  1.000020e+09       False    True           NaN         NaN     NaN
2  1.000048e+09        True    True  1.000048e+09        True    True
3  1.000058e+09        True    True  1.000058e+09        True    True
4  1.003620e+09        True    True  1.003620e+09       False    True

In [9]:
pop13_15.head()

,BBL,SiteEUI2013,"NYC Borough, Block and Lot (BBL)",SiteEUI2015,difference
0,1.013110e+09,125.4,1.013110e+09,49.3,-76.1
2,4.002520e+09,46.0,4.002520e+09,15.5,-30.5
4,1.007660e+09,122.3,1.007660e+09,140.1,17.8
5,1.008150e+09,117.0,1.008150e+09,117.6,0.6
41,1.005050e+09,82.1,1.005050e+09,88.5,6.4

In [10]:
pop14_16.head()

            BBL  SiteEUI2014  BBL - 10 digits  SiteEUI2016  difference
1  4.002520e+09         14.8     4.002520e+09         13.7        -1.1
2  3.009748e+09        102.3     3.009748e+09        105.9         3.6
3  4.032938e+09         44.6     4.032938e+09         49.9         5.3
4  4.000540e+09         25.8     4.000540e+09         31.3         5.5
5  4.096490e+09         89.5     4.096490e+09         96.4         6.9

In [174]:
# load LL87 retro-commissioning data
RCx13 = pd.read_csv('2013RCxBBL.csv')
RCx14 = pd.read_csv('2014RCxBBL.csv')
RCX15 = pd.read_csv('2015RCxBBL.csv')

In [175]:
# create column showing that retro-commissioning occurred in 2013
RCx13['RCx13'] = 1
RCx14['RCx14'] = 1
RCx15['RCx15'] = 1

# convert BBL to integer so the inner merge will work 
RCx13['BBL'] = RCx13['BBL'].astype(int)
pop12_14['BBL'] = pop12_14['BBL'].astype(int)

RCx14['BBL'] = RCx14['BBL'].astype(int)
pop13_15['BBL'] = pop13_15['BBL'].astype(int)

RCx15['BBL'] = RCx15['BBL'].astype(int)
pop14_16['BBL'] = pop14_16['BBL'].astype(int)

# merge with appropriate pop dataframe
pop12_14 = pd.merge(pop12_14, RCx13, how='left', on=['BBL', 'BBL'])
pop13_15 = pd.merge(pop13_15, RCx14, how='left', on=['BBL', 'BBL'])
pop14_16 = pd.merge(pop14_16, RCx15, how='left', on=['BBL', 'BBL'])

pop12_14.describe()

NameError: name 'RCx15' is not defined

In [363]:
pop12_14.shape

(9389, 5)

In [364]:
# sample df is made of records where RCx occurred
sample12_14 = pop12_14.dropna()
population12_14 = pop12_14[pop12_14.RCx13 != 1]

sample13_15 = pop13_15.dropna()
population13_15 = pop13_15[pop13_15.RCx14 != 1]

sample14_16 = pop14_16.dropna()
population14_16 = pop14_16[pop14_16.RCx15 != 1]

population12_14

             BBL  SiteEUI2012  SiteEUI2014  difference  RCx13
0     1000047501        102.0        149.0        47.0    NaN
1     1000057501        119.6        113.8        -5.8    NaN
2     1000090001         99.5         81.3       -18.2    NaN
3     1000090014         79.7         80.8         1.1    NaN
4     1000090029        139.4        136.2        -3.2    NaN
5     1000100014        134.5        113.0       -21.5    NaN
6     1000100023        102.8        106.8         4.0    NaN
9     1000130005         80.1         99.8        19.7    NaN
10    1011200022         62.4         65.4         3.0    NaN
11    1000157501         28.7         66.6        37.9    NaN
12    1000157501         50.0         66.6        16.6    NaN
13    1000157502         50.1         78.0        27.9    NaN
14    3068180025         49.7         66.9        17.2    NaN
15    1011860091         60.9         68.6         7.7    NaN
17    1000160120        111.2        113.6         2.4    NaN
18    1000160150         31.4         10.4       -21.0    NaN
19    1000160180        112.4        108.7        -3.7    NaN
20    1000160185         96.3         89.9        -6.4    NaN
21    1000160190         70.3         50.0       -20.3    NaN
22    1000160195        100.5        105.9         5.4    NaN
23    1000160200         80.9         96.6        15.7    NaN
24    1000160210         72.2         77.5         5.3    NaN
25    1000160225        148.3        113.8       -34.5    NaN
26    1000160260        111.5        109.7        -1.8    NaN
27    1000167501         64.9         77.0        12.1    NaN
28    1000167502         71.5         41.1       -30.4    NaN
29    1009087501         68.4         88.7        20.3    NaN
30    1009087501        120.6         88.7       -31.9    NaN
31    1000167504         74.6         73.3        -1.3    NaN
32    1000167505        116.7        106.7       -10.0    NaN
...          ...          ...          ...         ...    ...
9342  5024507506         80.1         77.3        -2.8    NaN
9343  4002860001         34.2         37.0         2.8    NaN
9344  4002900025         35.5         51.7        16.2    NaN
9346  5026380050        115.8        117.2         1.4    NaN
9347  5026380060         68.6         88.4        19.8    NaN
9348  5027050225        194.4        213.3        18.9    NaN
9349  5028000037         22.5         54.0        31.5    NaN
9350  5028320017        103.9         86.9       -17.0    NaN
9351  4017820019         86.0        111.2        25.2    NaN
9352  4025850021         36.6         63.5        26.9    NaN
9353  5028710001         68.6         68.8         0.2    NaN
9355  5028940001         84.3         68.8       -15.5    NaN
9356  5029220020        105.8         91.7       -14.1    NaN
9357  5030950021         49.5         51.4         1.9    NaN
9358  5030950021         63.9         51.4       -12.5    NaN
9359  5031570001         54.3         49.8        -4.5    NaN
9360  5033070025         82.6         85.7         3.1    NaN
9363  5039690001         49.0         57.3         8.3    NaN
9377  5013800001         94.0        105.5        11.5    NaN
9378  5040010001        164.6         93.8       -70.8    NaN
9379  5052360031         72.9        169.5        96.6    NaN
9380  5054970007        196.5        266.6        70.1    NaN
9381  5054970007        237.3        266.6        29.3    NaN
9382  5059650084          9.4         15.5         6.1    NaN
9383  5063320006         58.7         53.3        -5.4    NaN
9384  5070670117         13.3         16.2         2.9    NaN
9385  5071000028        264.8        229.1       -35.7    NaN
9386  5074810001         80.8         84.9         4.1    NaN
9387  5075110001        113.9        164.5        50.6    NaN
9388  5079910100        135.9        161.6        25.7    NaN

[8103 rows x 5 columns]

In [365]:
sample12_14_diff = sample12_14['difference']
sample13_15_diff = sample13_15['difference']
sample14_16_diff = sample14_16['difference']

sample12_14_diff.describe()

count    1286.000000
mean        7.270684
std        34.651884
min      -247.400000
25%        -3.700000
50%         6.550000
75%        16.650000
max       165.900000
Name: difference, dtype: float64

In [366]:
pop12_14_diff = pop12_14['difference']
pop13_15_diff = pop13_15['difference']
pop14_16_diff = pop14_16['difference']

pop12_14_diff.describe()

count    9389.000000
mean       10.255522
std        34.166897
min      -247.400000
25%        -0.800000
50%         8.500000
75%        19.700000
max       280.100000
Name: difference, dtype: float64

In [367]:
# using scipy.stats.ttest_ind_from_stats
# arguments includ: ttest_ind_from_stats(mean1, std1, nobs1, mean2, std2, nobs2, equal_var=True)
ttest13 = ttest_ind_from_stats(pop12_14_diff.mean(), pop12_14_diff.std(), pop12_14_diff.count(), 
                             sample12_14_diff.mean(), sample12_14_diff.std(), sample12_14_diff.count())

ttest14 = ttest_ind_from_stats(pop13_15_diff.mean(), pop13_15_diff.std(), pop13_15_diff.count(), 
                             sample13_15_diff.mean(), sample13_15_diff.std(), sample13_15_diff.count())

ttest15 = ttest_ind_from_stats(pop14_16_diff.mean(), pop14_16_diff.std(), pop14_16_diff.couznt(), 
                             sample14_16_diff.mean(), sample14_16_diff.std(), sample14_16_diff.count())

In [368]:
ttest13

Ttest_indResult(statistic=2.9330216349513893, pvalue=0.0033639417642690041)

In [ ]:
ttest14

In [ ]:
ttest15